require "plugins"
require "options"
require "keymaps"
require "theme"
require "bottomLine"
require "treesitter"
require "directoryTree"
require "bar"
require "wildmenu"
require "scroll"
require "completion"
require "autopairs"
require "sneak"

-- LPSs
require "lsp.tsserver"
require "lsp.nullLs"
